+ python3 duplicate_finder.py --path /share/lasallelab/Annie/
md5sum: /share/lasallelab/Annie/Annie_Microglia_p35MAA/Window_permeth_readcentric_mod2.pl: Permission denied
Traceback (most recent call last):
  File "duplicate_finder.py", line 63, in <module>
    checksum_byte = subprocess.check_output(['md5sum', f'{key}'])
  File "/software/anaconda3/4.8.3/lssc0-linux/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/software/anaconda3/4.8.3/lssc0-linux/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['md5sum', '/share/lasallelab/Annie/Annie_Microglia_p35MAA/Window_permeth_readcentric_mod2.pl']' returned non-zero exit status 1.
